CREATE TABLE organizer_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    company_name VARCHAR(120) NOT NULL,
    company_email VARCHAR(254) NOT NULL UNIQUE,
    company_phone VARCHAR(10) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_organizer_profiles_company_phone ON organizer_profiles(company_phone);
