CREATE TABLE saga_instances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    zone_id BIGINT NOT NULL,
    total_amount DECIMAL(19,4) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE saga_instance_seat_ids (
    saga_instance_id BIGINT NOT NULL REFERENCES saga_instances(id),
    seat_id BIGINT NOT NULL
);

CREATE INDEX idx_saga_instances_status_updated_at ON saga_instances(status, updated_at);
