CREATE TABLE saga_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saga_instance_id BIGINT NOT NULL REFERENCES saga_instances(id),
    step VARCHAR(50) NOT NULL,
    payload_json TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_saga_outbox_saga_instance_id ON saga_outbox(saga_instance_id);
