CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50) NOT NULL UNIQUE,
    password_hash varchar(100) NOT NULL,
    organizer boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS venue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    city varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS area (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id bigint NOT NULL REFERENCES venue (id),
    name varchar(50) NOT NULL,
    rank int NOT NULL,
    UNIQUE (venue_id, name)
);

CREATE TABLE IF NOT EXISTS seat (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_id bigint NOT NULL REFERENCES area (id),
    row_label varchar(5) NOT NULL,
    row_rank int NOT NULL,
    number int NOT NULL,
    UNIQUE (area_id, row_label, number)
);

CREATE TABLE IF NOT EXISTS event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id bigint NOT NULL REFERENCES venue (id),
    organizer_id bigint NOT NULL REFERENCES users (id),
    title varchar(150) NOT NULL,
    starts_at timestamptz NOT NULL,
    ends_at timestamptz NOT NULL,
    booking_opens_at timestamptz NOT NULL,
    booking_closes_at timestamptz NOT NULL,
    max_per_person int NOT NULL,
    status varchar(20) NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED', 'CANCELLED')),
    category varchar(30) NOT NULL,
    tagline varchar(200) NOT NULL,
    description text NOT NULL,
    presented_by varchar(100) NOT NULL,
    language varchar(60) NOT NULL,
    age_guidance varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS performer (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES event (id),
    position int NOT NULL,
    name varchar(100) NOT NULL,
    role varchar(100) NOT NULL,
    UNIQUE (event_id, position)
);

CREATE TABLE IF NOT EXISTS event_area (
    event_id bigint NOT NULL REFERENCES event (id),
    area_id bigint NOT NULL REFERENCES area (id),
    version bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (event_id, area_id)
);

CREATE TABLE IF NOT EXISTS booking (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES event (id),
    user_id bigint NOT NULL REFERENCES users (id),
    request_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ticket (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id bigint NOT NULL REFERENCES booking (id),
    event_id bigint NOT NULL REFERENCES event (id),
    seat_id bigint NOT NULL REFERENCES seat (id),
    attendee_name varchar(100) NOT NULL,
    code varchar(10) NOT NULL UNIQUE,
    status varchar(20) NOT NULL CHECK (status IN ('VALID', 'USED', 'CANCELLED')),
    checked_in_at timestamptz,
    checked_in_by bigint REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS queue_request (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES event (id),
    area_id bigint NOT NULL REFERENCES area (id),
    user_id bigint NOT NULL REFERENCES users (id),
    group_size int NOT NULL CHECK (group_size > 0),
    split_ok boolean NOT NULL DEFAULT false,
    request_id uuid NOT NULL,
    status varchar(20) NOT NULL CHECK (status IN ('WAITING', 'SEATED', 'LEFT', 'CLOSED')),
    joined_at timestamptz NOT NULL DEFAULT now(),
    booking_id bigint REFERENCES booking (id),
    attendee_names text[] NOT NULL
);

CREATE TABLE IF NOT EXISTS staff_assignment (
    event_id bigint NOT NULL REFERENCES event (id),
    user_id bigint NOT NULL REFERENCES users (id),
    PRIMARY KEY (event_id, user_id)
);

ALTER TABLE ticket DROP CONSTRAINT IF EXISTS ticket_status_check;
ALTER TABLE ticket ADD CONSTRAINT ticket_status_check CHECK (status IN ('HELD', 'VALID', 'USED', 'CANCELLED'));

CREATE UNIQUE INDEX IF NOT EXISTS ticket_seat_live
    ON ticket (event_id, seat_id)
    WHERE status IN ('HELD', 'VALID', 'USED');

DROP INDEX IF EXISTS ticket_seat_active;

CREATE UNIQUE INDEX IF NOT EXISTS booking_request
    ON booking (user_id, request_id);

CREATE UNIQUE INDEX IF NOT EXISTS queue_request_request
    ON queue_request (user_id, request_id);

CREATE UNIQUE INDEX IF NOT EXISTS queue_one_waiting
    ON queue_request (event_id, user_id)
    WHERE status = 'WAITING';

ALTER TABLE users ADD COLUMN IF NOT EXISTS email varchar(254);

CREATE UNIQUE INDEX IF NOT EXISTS users_email
    ON users (lower(email));

CREATE TABLE IF NOT EXISTS rate_hit (
    key varchar(120) NOT NULL,
    window_start timestamptz NOT NULL,
    hits int NOT NULL,
    PRIMARY KEY (key, window_start)
);

CREATE TABLE IF NOT EXISTS notification (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users (id),
    kind varchar(20) NOT NULL,
    ref_id bigint NOT NULL,
    status varchar(10) NOT NULL DEFAULT 'PENDING',
    created_at timestamptz NOT NULL DEFAULT now(),
    sent_at timestamptz,
    error varchar(300),
    UNIQUE (user_id, kind, ref_id)
);

CREATE INDEX IF NOT EXISTS notification_pending
    ON notification (id)
    WHERE status = 'PENDING';

CREATE TABLE IF NOT EXISTS spring_session (
    primary_id char(36) NOT NULL PRIMARY KEY,
    session_id char(36) NOT NULL,
    creation_time bigint NOT NULL,
    last_access_time bigint NOT NULL,
    max_inactive_interval int NOT NULL,
    expiry_time bigint NOT NULL,
    principal_name varchar(100)
);

CREATE UNIQUE INDEX IF NOT EXISTS spring_session_ix1 ON spring_session (session_id);
CREATE INDEX IF NOT EXISTS spring_session_ix2 ON spring_session (expiry_time);
CREATE INDEX IF NOT EXISTS spring_session_ix3 ON spring_session (principal_name);

CREATE TABLE IF NOT EXISTS spring_session_attributes (
    session_primary_id char(36) NOT NULL REFERENCES spring_session (primary_id) ON DELETE CASCADE,
    attribute_name varchar(200) NOT NULL,
    attribute_bytes bytea NOT NULL,
    PRIMARY KEY (session_primary_id, attribute_name)
);

ALTER TABLE notification ADD COLUMN IF NOT EXISTS claimed_at timestamptz;

ALTER TABLE notification ADD COLUMN IF NOT EXISTS attempts int NOT NULL DEFAULT 0;
ALTER TABLE notification ADD COLUMN IF NOT EXISTS next_attempt_at timestamptz;

CREATE TABLE IF NOT EXISTS password_reset (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users (id),
    token_hash char(64) NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE event ADD COLUMN IF NOT EXISTS waiting_room boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS waiting_room (
    event_id bigint NOT NULL REFERENCES event (id),
    user_id bigint NOT NULL REFERENCES users (id),
    joined_at timestamptz NOT NULL DEFAULT now(),
    position int,
    admitted_at timestamptz,
    pass_expires_at timestamptz,
    done_at timestamptz,
    PRIMARY KEY (event_id, user_id)
);

CREATE INDEX IF NOT EXISTS waiting_room_next
    ON waiting_room (event_id, position)
    WHERE admitted_at IS NULL;

ALTER TABLE event_area ADD COLUMN IF NOT EXISTS price_paise bigint NOT NULL DEFAULT 0;
ALTER TABLE ticket ADD COLUMN IF NOT EXISTS price_paise bigint NOT NULL DEFAULT 0;
ALTER TABLE booking ADD COLUMN IF NOT EXISTS amount_paise bigint NOT NULL DEFAULT 0;
ALTER TABLE booking ADD COLUMN IF NOT EXISTS pay_status varchar(10);
ALTER TABLE booking ADD COLUMN IF NOT EXISTS held_until timestamptz;
ALTER TABLE booking ADD COLUMN IF NOT EXISTS order_id varchar(40) UNIQUE;
ALTER TABLE booking ADD COLUMN IF NOT EXISTS payment_id varchar(40) UNIQUE;
ALTER TABLE booking ADD COLUMN IF NOT EXISTS paid_at timestamptz;

CREATE INDEX IF NOT EXISTS booking_held
    ON booking (held_until)
    WHERE pay_status = 'HELD';

CREATE TABLE IF NOT EXISTS payment_event (
    event_id varchar(80) PRIMARY KEY,
    received_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS refund (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id bigint NOT NULL REFERENCES booking (id),
    payment_id varchar(40) NOT NULL,
    amount_paise bigint NOT NULL,
    reason varchar(20) NOT NULL,
    status varchar(10) NOT NULL DEFAULT 'PENDING',
    attempts int NOT NULL DEFAULT 0,
    next_attempt_at timestamptz,
    refund_id varchar(40),
    error varchar(300),
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at timestamptz;

CREATE TABLE IF NOT EXISTS email_verification (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users (id),
    token_hash char(64) NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);
