CREATE TABLE ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_account_id BIGINT NOT NULL REFERENCES wallet_accounts(id),
    type VARCHAR(20) NOT NULL,
    amount NUMERIC(19,4) NOT NULL CHECK (amount > 0),
    balance_after NUMERIC(19,4) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    reference VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_ledger_wallet_idempotency_type UNIQUE (wallet_account_id, idempotency_key, type)
);

CREATE INDEX idx_ledger_entries_wallet_account ON ledger_entries(wallet_account_id);
