CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    zone_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'HELD',
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    confirmed_at TIMESTAMP WITH TIME ZONE,
    token VARCHAR(64) NOT NULL UNIQUE
);

CREATE INDEX idx_reservations_status_expires ON reservations(status, expires_at);
CREATE INDEX idx_reservations_user_event ON reservations(user_id, event_id);

CREATE TABLE reservation_seats (
    reservation_id BIGINT NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
    seat_id BIGINT NOT NULL
);

CREATE INDEX idx_reservation_seats_reservation ON reservation_seats(reservation_id);
