CREATE TABLE IF NOT EXISTS staff_assignments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        BIGINT NOT NULL REFERENCES events(id),
    user_id         BIGINT NOT NULL,
    status          VARCHAR(16) NOT NULL,
    invited_by      BIGINT NOT NULL,
    invited_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    responded_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_staff_assignment_event_user UNIQUE (event_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_staff_assignments_event_id ON staff_assignments(event_id);
CREATE INDEX IF NOT EXISTS idx_staff_assignments_event_user_status ON staff_assignments(event_id, user_id, status);
